# frozen_string_literal: true

module Constants
  USER_START_BANK = 100
  DEALER_START_BANK = 100
  BLACK_JACK = 21

  CARDS = { 1 => { value: 2, pic: '2♥️' },
            2 => { value: 3, pic: '3♥️' },
            3 => { value: 4, pic: '4♥️' },
            4 => { value: 5, pic: '5♥️' },
            5 => { value: 6, pic: '6♥️' },
            6 => { value: 7, pic: '7♥️' },
            7 => { value: 8, pic: '8♥️' },
            8 => { value: 9, pic: '9♥️' },
            9 => { value: 10, pic: '10♥️' },
            10 => { value: 10, pic: 'J♥️' },
            11 => { value: 10, pic: 'Q♥️' },
            12 => { value: 10, pic: 'K♥️' },
            13 => { value: nil, pic: 'A♥️' },
            14 => { value: 2, pic: '2♦️' },
            15 => { value: 3, pic: '3♦️' },
            16 => { value: 4, pic: '4♦️' },
            17 => { value: 5, pic: '5♦️' },
            18 => { value: 6, pic: '6♦️' },
            19 => { value: 7, pic: '7♦️' },
            20 => { value: 8, pic: '8♦️' },
            21 => { value: 9, pic: '9♦️' },
            22 => { value: 10, pic: '10♦️' },
            23 => { value: 10, pic: 'J♦️' },
            24 => { value: 10, pic: 'Q♦️' },
            25 => { value: 10, pic: 'K♦️' },
            26 => { value: nil, pic: 'A♦️' },
            27 => { value: 2, pic: '2♣️' },
            28 => { value: 3, pic: '3♣️' },
            29 => { value: 4, pic: '4♣️' },
            30 => { value: 5, pic: '5♣️' },
            31 => { value: 6, pic: '6♣️' },
            32 => { value: 7, pic: '7♣️' },
            33 => { value: 8, pic: '8♣️' },
            34 => { value: 9, pic: '9♣️' },
            35 => { value: 10, pic: '10♣️' },
            36 => { value: 10, pic: 'J♣️' },
            37 => { value: 10, pic: 'Q♣️' },
            38 => { value: 10, pic: 'K♣️' },
            39 => { value: nil, pic: 'A♣️' },
            40 => { value: 2, pic: '2♠️' },
            41 => { value: 3, pic: '3♠️' },
            42 => { value: 4, pic: '4♠️' },
            43 => { value: 5, pic: '5♠️' },
            44 => { value: 6, pic: '6♠️' },
            45 => { value: 7, pic: '7♠️' },
            46 => { value: 8, pic: '8♠️' },
            47 => { value: 9, pic: '9♠️' },
            48 => { value: 10, pic: '10♠️' },
            49 => { value: 10, pic: 'J♠️' },
            50 => { value: 10, pic: 'Q♠️' },
            51 => { value: 10, pic: 'K♠️' },
            52 => { value: nil, pic: 'A♠️' } }.freeze

  GREETING = 'Welcome to BlackJack table'
end
