# frozen_string_literal: true

module Constants
  USER_START_BANK = 100
  DEALER_START_BANK = 100

  CARDS = [{ id: 1, value: 2, pic: '2♥️' },
           { id: 2, value: 3, pic: '3♥️' },
           { id: 3, value: 4, pic: '4♥️' },
           { id: 4, value: 5, pic: '5♥️' },
           { id: 5, value: 6, pic: '6♥️' },
           { id: 6, value: 7, pic: '7♥️' },
           { id: 7, value: 8, pic: '8♥️' },
           { id: 8, value: 9, pic: '9♥️' },
           { id: 9, value: 10, pic: '10♥️' },
           { id: 10, value: 10, pic: 'J♥️' },
           { id: 11, value: 10, pic: 'Q♥️' },
           { id: 12, value: 10, pic: 'K♥️' },
           { id: 13, value: nil, pic: 'A♥️' },
           { id: 14, value: 2, pic: '2♦️' },
           { id: 15, value: 3, pic: '3♦️' },
           { id: 16, value: 4, pic: '4♦️' },
           { id: 17, value: 5, pic: '5♦️' },
           { id: 18, value: 6, pic: '6♦️' },
           { id: 19, value: 7, pic: '7♦️' },
           { id: 20, value: 8, pic: '8♦️' },
           { id: 21, value: 9, pic: '9♦️' },
           { id: 22, value: 10, pic: '10♦️' },
           { id: 23, value: 10, pic: 'J♦️' },
           { id: 24, value: 10, pic: 'Q♦️' },
           { id: 25, value: 10, pic: 'K♦️' },
           { id: 26, value: nil, pic: 'A♦️' },
           { id: 27, value: 2, pic: '2♣️' },
           { id: 28, value: 3, pic: '3♣️' },
           { id: 29, value: 4, pic: '4♣️' },
           { id: 30, value: 5, pic: '5♣️' },
           { id: 31, value: 6, pic: '6♣️' },
           { id: 32, value: 7, pic: '7♣️' },
           { id: 33, value: 8, pic: '8♣️' },
           { id: 34, value: 9, pic: '9♣️' },
           { id: 35, value: 10, pic: '10♣️' },
           { id: 36, value: 10, pic: 'J♣️' },
           { id: 37, value: 10, pic: 'Q♣️' },
           { id: 38, value: 10, pic: 'K♣️' },
           { id: 39, value: nil, pic: 'A♣️' },
           { id: 40, value: 2, pic: '2♠️' },
           { id: 41, value: 3, pic: '3♠️' },
           { id: 42, value: 4, pic: '4♠️' },
           { id: 43, value: 5, pic: '5♠️' },
           { id: 44, value: 6, pic: '6♠️' },
           { id: 45, value: 7, pic: '7♠️' },
           { id: 46, value: 8, pic: '8♠️' },
           { id: 47, value: 9, pic: '9♠️' },
           { id: 48, value: 10, pic: '10♠️' },
           { id: 49, value: 10, pic: 'J♠️' },
           { id: 50, value: 10, pic: 'Q♠️' },
           { id: 51, value: 10, pic: 'K♠️' },
           { id: 52, value: nil, pic: 'A♠️' }].freeze

  GREETING = 'Welcome to BlackJack table'
end
